development:
  adapter: postgresql
  database: ticketee_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: ticketee_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: ticketee_production
  pool: 5
  timeout: 5000
